### ISSUE TITLE
WinHttpException: A security error occurred / The buffers supplied to a function was too small

### ISSUE THREAD

**Issue by justdmitry** [iflight/RequestLogger.AzureTable#12]
Две ошибки, частость появления одинаковая:

```
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A security error occurred
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__103.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at iflight.RequestLogger.AzureTable.LoggingHandler.<SendAsync>d__2.MoveNext()
```

```
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The buffers supplied to a function was too small
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__103.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at iflight.RequestLogger.AzureTable.LoggingHandler.<SendAsync>d__2.MoveNext()
```

`net461`, `RequestLogger.AzureTable 0.4.3`, `Microsoft.WindowsAzure.Storage 6.2.2`, `Microsoft.Extensions.Logging 1.1.2`

**Comment by justdmitry** [comment]
Корни уходят в corefx: https://github.com/dotnet/corefx/issues/7812, пока не нашли причин и соответственно нет идей по workaround

**Comment by davidsh** [comment]
Regarding https://github.com/dotnet/corefx/issues/7812, if you have a repro for this, please post it for us.  We have been unable to reliably repro the problem which is why we have no fix for it yet.  Thanks!

**Comment by justdmitry** [comment]
Судя по всему [найден "обходной путь"](https://github.com/dotnet/corefx/issues/7812#issuecomment-307088860) - принудительно обновить `System.Net.Http` до `v4.3.2` (вместо автоматически подхватываемой 4.3.0). Предлагаю на этом закрыть багу,
